services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
    container_name: e-ticket-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        NODE_ENV: production
    container_name: e-ticket-prod
    ports:
      - "8080:3000"
